# Generated by Django 5.0.6 on 2024-07-10 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelformapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('rating', models.IntegerField()),
                ('cast', models.CharField(max_length=38)),
                ('release', models.CharField(max_length=10)),
                ('gener', models.CharField(max_length=35)),
            ],
        ),
        migrations.DeleteModel(
            name='Moviedata',
        ),
    ]
